# Generated by Django 4.0.3 on 2022-03-19 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQ', 'Pendiente'), ('APR', 'Aprobado'), ('ONR', 'En ruta'), ('DEL', 'Entregado'), ('RET', 'Devuelto')], default='REQ', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='webapp.device')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
