# Generated by Django 4.0.3 on 2022-03-20 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_alter_borrow_carrier_id_alter_borrow_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='carrier_id',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'mensajeros'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
